name: fastpages
channels: 
    - conda-forge
dependencies:
    - python=3.7
    - pandas>=1.0.0
    - matplotlib
    - seaborn
    - scikit-learn>=0.22.2
    - ipywidgets
    - pyzmq
    - altair>=4.0.1
    - vega_datasets
    - folium
    
    